{% set name = "dit" %}
{% set version = "1.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: fa9972ea1082ae594d53d1518fd1bb3679a4b844bc13c90e646e68232d7f9092

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python
  run:
    - boltons
    - contextlib2
    - debtcollector
    - networkx
    - numpy >=1.11
    - prettytable
    - python  <3.7
    - scipy >=0.15.0
    - six >=1.4.0

test:
  imports:
    - dit
    - dit.algorithms
    - dit.divergences
    - dit.example_dists
    - dit.inference
    - dit.math
    - dit.multivariate
    - dit.multivariate.common_informations
    - dit.multivariate.secret_key_agreement
    - dit.other
    - dit.pid
    - dit.pid.distributions
    - dit.profiles
    - dit.rate_distortion
    - dit.shannon
    - dit.utils

about:
  home: http://dit.io
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Python package for information theory.
  description: |
    Information theory is a powerful extension to probability and statistics, quantifying dependencies among 
    arbitrary random variables in a way that is consistent and comparable across systems and scales. Information 
    theory was originally developed to quantify how quickly and reliably information could be transmitted across 
    an arbitrary channel. The demands of modern, data-driven science have been coopting and extending these 
    quantities and methods into unknown, multivariate settings where the interpretation and best practices 
    are not known. For example, there are at least four reasonable multivariate generalizations of the mutual 
    information, none of which inherit all the interpretations of the standard bivariate case. Which is best 
    to use is context-dependent. dit implements a vast range of multivariate information measures in an effort to allow 
    information practitioners to study how these various measures behave and interact in a variety of contexts. 
    We hope that having all these measures and techniques implemented in one place will allow the development of 
    robust techniques for the automated quantification of dependencies within a system and concrete interpretation 
    of what those dependencies mean.
  doc_url: http://docs.dit.io/en/latest/
  dev_url: https://github.com/dit/dit

extra:
  recipe-maintainers:
    - volpatto
    - Autoplectic
