travis:
  secure:
    BINSTAR_TOKEN: BlEcjO5/YffNmQO7/iO51Ga71Jcm9VnOs746xthJxQfSeIZRcKCNZB7a+GgGB7xudTJyO6GxcXhA2RoPa6vOZeJlQmdsNcHOvieWkslKkhomHstKK2ZbTlqxFuixU7RYnUTJuif5tAc9yEwUd8Sig4otDzOHybJ0YvEFnCvdm9rYzJPvVXo3FVprjwSAoQy7ORlHmKh0TShAoNQtOB/xIhIvi5YiibB007hhr+VVtqbPKN+ppzTaNcGr3L0j3mldYRLe18l5XZ6v5wvM81uFOeGSeQ+lmDqyFHChyN9/8gyh94neasmJOZYguXjouQC9ug6bfUsy6SF9FScOsDV/q2gsvhC7HuBP7wQbis3U4GORBY8yW2yicoJoizlg6Kk2wkO51a0lAHhziyogYLmB87RcmbsoWOIYf1J2HNju+YVLS+WhQPy6asOCy+GwJP7WOh6cMH+laDgocJlq9uWsiOfi0d/IowLx4mE1oCSnPGxb8F269YrvhG77G+4uT0D34lDWRGYqeuDxAGIPHYnJmeP0JrLP2qT6B1C7MimelUjRIqX7yAsI/Cg8gfvggY+dX2BI96x8cOyH4DKXaL2xtrbAY0oFjo1WbYc9gFoxtH4zQ7w5x9AmlZsuJE9hemFg6YGofFtdjspyhciSyWK+3zdmX+6WL5daJjfu4NHlArg=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
